import "server-only";

import {
  Configuration,
  SendApi,
  type V1SendRequest,
} from "hostinger-mail-api-sdk";

import { SITE_NAME } from "@/lib/site";

import { emails, type EmailName } from "./generated";

/**
 * Sends one of the site's emails from the paradize.space mailbox through
 * the Hostinger Mail API.
 *
 * It takes the name of a template, never content. Every email the site
 * sends is a Maizzle template in emails/, compiled into ./generated by
 * scripts/build-emails.mjs. There is no parameter for hand-written HTML,
 * and ESLint keeps the mail SDK out of every other file, so nothing can
 * send around it.
 *
 * It goes out from a real mailbox, so a reply lands in that inbox, and
 * the API keeps a copy in its Sent folder. The mailbox's SPF and DKIM
 * records are Hostinger's own, so no DNS change is needed.
 *
 * TO CONNECT
 * ----------
 * HOSTINGER_MAIL_TOKEN       hPanel → Emails → the domain → Agentic Mail →
 *                            API access. Server-side only.
 * HOSTINGER_MAIL_MAILBOX_ID  the mailbox's `resourceId` (AC…), listed by
 *                            GET https://api.mail.hostinger.com/api/v1/me
 */

export type SendResult =
  | { status: "sent" }
  | { status: "unconfigured" }
  | { status: "error"; message: string };

export async function sendEmail(
  to: string,
  name: EmailName,
): Promise<SendResult> {
  const token = process.env.HOSTINGER_MAIL_TOKEN;
  const mailbox = process.env.HOSTINGER_MAIL_MAILBOX_ID;
  if (!token || !mailbox) return { status: "unconfigured" };

  const email = emails[name];

  // The SDK's generated type marks every field required (cc, attachments,
  // the reply references); Hostinger's API reference makes all but a
  // recipient optional. Only the fields an email uses are sent.
  const request = {
    to: [to],
    displayName: SITE_NAME,
    subject: email.subject,
    html: email.html,
    text: email.text,
  } satisfies Partial<V1SendRequest>;

  try {
    // Resolves on 204: sent, and saved to the mailbox's Sent folder.
    // Anything else rejects.
    await new SendApi(new Configuration({ accessToken: token })).sendEmail(
      mailbox,
      request as V1SendRequest,
      { timeout: 8000 },
    );
    return { status: "sent" };
  } catch (error) {
    return { status: "error", message: describeFailure(error) };
  }
}

/**
 * Names a failed send by its HTTP status and error code only. The SDK
 * rejects with an axios error, which also carries the request: the
 * Authorization header with the token, and the body with the recipient.
 * Hostinger's error body can echo the recipient back too. These messages
 * end up in Vercel's logs, so the error itself is never logged.
 */
function describeFailure(error: unknown): string {
  const failure = error as {
    code?: unknown;
    response?: { status?: number; data?: { code?: unknown } };
  } | null;

  // No response at all: a timeout (ECONNABORTED) or a network failure.
  if (!failure?.response) {
    const code = typeof failure?.code === "string" ? failure.code : "no code";
    return `Hostinger Mail request failed (${code}).`;
  }

  const { status, data } = failure.response;
  const code = typeof data?.code === "string" ? data.code : "no code";
  return `Hostinger Mail responded with ${status} (${code}).`;
}
