/**
 * Compiles every Maizzle template in emails/ into lib/emails/generated.ts,
 * the only email content the server code can send.
 *
 * It runs before `next dev`, `next build` and `tsc` (see package.json), so
 * the output is never stale and never edited by hand. The file is not
 * committed. To change an email, change its .vue template.
 *
 * Each template must set its subject with `defineConfig({ subject })` and
 * carry a <Plaintext> part; the build fails rather than ship an email
 * without either.
 */
import { glob, mkdir, writeFile } from "node:fs/promises";
import { basename, dirname, relative } from "node:path";

import { createMaizzle, resolveConfig } from "@maizzle/framework";

const OUTPUT = "lib/emails/generated.ts";

const config = await resolveConfig();

const files = [];
for (const pattern of config.content) {
  for await (const file of glob(pattern)) files.push(file);
}
files.sort();

if (files.length === 0) {
  throw new Error(`No email templates match ${config.content.join(", ")}.`);
}

const maizzle = await createMaizzle(config);
const emails = {};

try {
  for (const file of files) {
    const name = basename(file, ".vue");
    const where = relative(process.cwd(), file);
    const { html, plaintext, config: used } = await maizzle.render(file);

    if (typeof used.subject !== "string" || used.subject.trim() === "") {
      throw new Error(`${where}: set the subject with defineConfig({ subject }).`);
    }
    if (!plaintext || plaintext.trim() === "") {
      throw new Error(`${where}: add a <Plaintext> part.`);
    }

    emails[name] = { subject: used.subject, html, text: plaintext };
  }
} finally {
  await maizzle.close();
}

const source = `// GENERATED by scripts/build-emails.mjs from the Maizzle templates in
// emails/. Do not edit: it is rebuilt before every dev, build and
// typecheck run, and it is not committed. Change the .vue template.

export const emails = ${JSON.stringify(emails, null, 2)} as const satisfies Record<
  string,
  { subject: string; html: string; text: string }
>;

export type EmailName = keyof typeof emails;
`;

await mkdir(dirname(OUTPUT), { recursive: true });
await writeFile(OUTPUT, source);

console.log(
  `emails: compiled ${Object.keys(emails).join(", ")} into ${OUTPUT}`,
);
